### ISSUE TITLE
Add ANSI support for Subtract

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#535]
### What is the problem the feature request solves?

Spark has specific handling of overflows when ANSI mode is enabled and we need to add the same in Comet.

**Comment by andygrove** [comment]
https://github.com/apache/datafusion-comet/issues/535

**Comment by planga82** [comment]
I want to try this one!

**Comment by dharanad** [comment]
Hello @andygrove I would like to work on this issue. Can you please assign it to me

**Comment by dharanad** [comment]
take

**Comment by dharanad** [comment]
Hello @andygrove ,  I noticed that enabling ANSI mode is causing the subtraction operation to throw an arithmetic exception at runtime. I'm wondering if there's a specific expected behavior for this task in ANSI mode.


```
scala> spark.conf.set("spark.sql.ansi.enabled", true)

scala> spark.sql("select * from t").show
+-----------+---+
|          a|  b|
+-----------+---+
|          4| 40|
|          2| 20|
|          1| 10|
|          3| 30|
|-2147483648|  1|
+-----------+---+

scala> spark.sql("select a - b from t").show
24/06/24 21:56:22 ERROR Executor: Exception in task 3.0 in stage 10.0 (TID 25)
org.apache.spark.SparkArithmeticException: [ARITHMETIC_OVERFLOW] integer overflow. Use 'try_subtract' to tolerate overflow and return NULL instead. If necessary set "spark.sql.ansi.enabled" to "false" to bypass this error.
== SQL(line 1, position 8) ==
select a - b from t
       ^^^^^

        at org.apache.spark.sql.errors.QueryExecutionErrors$.arithmeticOverflowError(QueryExecutionErrors.scala:643)
        at org.apache.spark.sql.catalyst.util.MathUtils$.withOverflow(MathUtils.scala:86)
        at org.apache.spark.sql.catalyst.util.MathUtils$.subtractExact(MathUtils.scala:43)
        at org.apache.spark.sql.catalyst.util.MathUtils.subtractExact(MathUtils.scala)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:760)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:388)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:891)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:891)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:92)
        at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
        at org.apache.spark.scheduler.Task.run(Task.scala:139)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:554)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1529)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:557)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
24/06/24 21:56:22 WARN TaskSetManager: Lost task 3.0 in stage 10.0 (TID 25) (192.168.0.104 executor driver): org.apache.spark.SparkArithmeticException: [ARITHMETIC_OVERFLOW] integer overflow. Use 'try_subtract' to tolerate overflow and return NULL instead. If necessary set "spark.sql.ansi.enabled" to "false" to bypass this error.
== SQL(line 1, position 8) ==
select a - b from t
       ^^^^^

        at org.apache.spark.sql.errors.QueryExecutionErrors$.arithmeticOverflowError(QueryExecutionErrors.scala:643)
        at org.apache.spark.sql.catalyst.util.MathUtils$.withOverflow(MathUtils.scala:86)
        at org.apache.spark.sql.catalyst.util.MathUtils$.subtractExact(MathUtils.scala:43)
        at org.apache.spark.sql.catalyst.util.MathUtils.subtractExact(MathUtils.scala)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:760)
        at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:388)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:891)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:891)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:367)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:331)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:92)
        at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:161)
        at org.apache.spark.scheduler.Task.run(Task.scala:139)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:554)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1529)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:557)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

....

scala> spark.conf.set("spark.sql.ansi.enabled", false)

scala> spark.sql("select a - b from t").show
24/06/24 21:56:45 WARN CometSparkSessionExtensions$CometExecRule: Comet cannot execute some parts of this plan natively because CollectLimit is not supported
+----------+
|   (a - b)|
+----------+
|       -36|
|       -18|
|        -9|
|       -27|
|2147483647|
+----------+

```

I apologize for any confusion on my part. As I am new to this project

**Comment by coderfender** [comment]
@andygrove  This can be closed now since https://github.com/apache/datafusion-comet/pull/2136/ is merged to main
